[package]
name = "alkane"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "^0.10.0"
lazy_static = "^1.4.0"
limiting-factor = "^0.8.0"
log = "^0.4.17"
rocket = "^0.4.11"
rocket_codegen = "^0.4.11"
serde_yaml = "^0.9.21"

[dependencies.clap]
version = "~4.2.1"
features = ["derive"]

[dependencies.rocket_contrib]
version = "^0.4.11"
default-features = false
features = ["json"]

[dependencies.serde]
version = "^1.0.159"
features = ["derive"]
