#!/bin/sh

#   -------------------------------------------------------------
#   Alkane :: Example recipe to build a site
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   -------------------------------------------------------------

echo "Updated ....... $(date)" >> "$ALKANE_SITE_PATH"/hello
